In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('ds1.csv')

In [3]:
df.head()

id      A       B Res
0   0  3.532  4.7845   F
1   1  3.534  4.7766   F
2   2  3.537  4.8124   F
3   3  3.547  4.8304   F
4   4  3.541  4.8081   F

In [4]:
df.Res.value_counts()

F    850
T    150
Name: Res, dtype: int64

In [5]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [9]:
model = st.DecisionTreeClassifier()

In [10]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [11]:
model.score(X_test, y_test)

0.7303030303030303

In [12]:
y_pred = model.predict(X_test)

In [13]:
import sklearn.metrics as mt

In [14]:
mt.confusion_matrix(y_test, y_pred)

array([[231,  56],
       [ 33,  10]], dtype=int64)

# Transform the Data

In [15]:
f = open("newds.csv", "w")
f.write("A1,A2,B1,B2,Res\n")
a1=0
b1=0
for k,v in df.iterrows():
    f.write("{0},{1},{2},{3},{4}\n".format(a1,v.A,b1,v.B,v.Res))
    a1 = v.A
    b1 = v.B
f.close

<function TextIOWrapper.close()>

In [16]:
df = pd.read_csv('newds.csv')

In [17]:
df.head()

A1     A2      B1      B2 Res
0  0.000  3.532  0.0000  4.7845   F
1  3.532  3.534  4.7845  4.7766   F
2  3.534  3.537  4.7766  4.8124   F
3  3.537  3.547  4.8124  4.8304   F
4  3.547  3.541  4.8304  4.8081   F

In [18]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [22]:
model = st.DecisionTreeClassifier(min_samples_leaf=3)

In [23]:
model.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_leaf=3)

In [24]:
model.score(X_test, y_test)

0.7789115646258503

In [25]:
y_pred = model.predict(X_test)

In [26]:
import sklearn.metrics as mt

In [27]:
mt.confusion_matrix(y_test, y_pred)

array([[219,  34],
       [ 31,  10]], dtype=int64)

# Try 2

In [28]:
df = pd.read_csv('ds1.csv')

In [29]:
f = open("newds.csv", "w")
f.write("A1,A2,A3,B1,B2,B3,Res\n")
a1=0
b1=0
a2=0
b2=0
for k,v in df.iterrows():
    f.write("{0},{1},{2},{3},{4},{5},{6}\n".format(a1,a2,v.A,b1,b2,v.B,v.Res))
    a1 = a2
    b1 = b2
    a2 = v.A
    b2 = v.B
f.close

<function TextIOWrapper.close()>

In [30]:
df = pd.read_csv('newds.csv')

In [31]:
df.head()

A1     A2     A3      B1      B2      B3 Res
0  0.000  0.000  3.532  0.0000  0.0000  4.7845   F
1  0.000  3.532  3.534  0.0000  4.7845  4.7766   F
2  3.532  3.534  3.537  4.7845  4.7766  4.8124   F
3  3.534  3.537  3.547  4.7766  4.8124  4.8304   F
4  3.537  3.547  3.541  4.8124  4.8304  4.8081   F

In [32]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [35]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [36]:
model = st.DecisionTreeClassifier(min_samples_leaf=20)

In [37]:
model.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_leaf=20)

In [38]:
model.score(X_test, y_test)

0.8509933774834437

In [39]:
y_pred = model.predict(X_test)

In [40]:
import sklearn.metrics as mt

In [41]:
mt.confusion_matrix(y_test, y_pred)

array([[257,   0],
       [ 45,   0]], dtype=int64)

# Learn the Difference

In [42]:
df = pd.read_csv('ds1.csv')

In [43]:
f = open("newds.csv", "w")
f.write("A1,B1,Res\n")
a2=0
b2=0
for k,v in df.iterrows():
    f.write("{0},{1},{2}\n".format(v.A - a2,v.B-b2,v.Res))
    a2 = v.A
    b2 = v.B
f.close

<function TextIOWrapper.close()>

In [44]:
df = pd.read_csv('newds.csv')

In [45]:
df.head()

A1      B1 Res
0  3.532  4.7845   F
1  0.002 -0.0079   F
2  0.003  0.0358   F
3  0.010  0.0180   F
4 -0.006 -0.0223   F

In [46]:
X = df.drop(['Res'],axis=1)
y = df.Res

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [49]:
import sklearn.linear_model as sl
import sklearn.tree as st

In [50]:
model = st.DecisionTreeClassifier(min_samples_leaf=100)

In [51]:
model.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_leaf=100)

In [52]:
model.score(X_test, y_test)

0.8729096989966555

In [53]:
y_pred = model.predict(X_test)

In [54]:
import sklearn.metrics as mt

In [55]:
mt.confusion_matrix(y_test, y_pred)

array([[261,   0],
       [ 38,   0]], dtype=int64)